### ISSUE TITLE
Time and DateTime extensions

### ISSUE THREAD

**Issue by rubyworks** [rubyworks/facets#18]
Time and DateTime extensions need the most work. This has been put off for some time thinking that Ruby would get it's shit together and improve the situation. But it doesn't look like it will ever happen. So basically, at some point, some one needs to sit down study the current field --in particular ActiveSupport's methods, and polish up Facets' Time and DateTime extensions.

The elephant in room here is of course time zone support (ugh).

**Comment by ioquatix** [comment]
Can you elaborate a bit more on this @trans as I just provided comparison methods.

**Comment by ioquatix** [comment]
I don't think this is a huge issue right now. This gem is a collection of supporting functionality, people will contribute PRs on an as needed basis. Let's close this for now until someone has some actual tangible issue.
