### ISSUE TITLE
Reorg of Tests?

### ISSUE THREAD

**Issue by anithri** [rubyworks/facets#180]
The standards of the current documentation efforts seem to favor a test file for every way a method can be called.  Take String@snakecase, there is a alternate name for it called underscore that has it's own require file.  The snakecase code and the underscore require file each have a test file with a full set of code and a demo file with a full set of tests.  That is far from the only example, just in string, and some of them have different tests resulting from the slow migration and refactoring of methods over the years

I propose that in the case of tests we put test code only in the file that has actual code in it. That we be more transparent about which methods are aliases.  And that we make a point to have a full demo for way to invoke code (in other words snakecase and underscore should have separate demos, with maybe a note about the alias).

**Comment by trans** [comment]
That sounds good to me, although there should still be some testing of the alias to ensure it is in fact is the alias.

**Comment by anithri** [comment]
Ok, with the comments on #186 in mind, I'm going to restate the testing scheme.

1.  Methods in lib/foo/facets/bar/baz will be tested in test/foo/bar/baz.
2.  If lib/foo/facets/bar/baz consists only of a require statement, no test file is expected.
3.  If lib/foo/facets/bar/baz provides nothing but an optional require and an alias will have a test in test/foo/bar/baz, but only what is needed to test the existence of the alias and not the underlying code.
4.  Methods in lib/foo/facets/bar/baz will be demoed in demo/foo/bar/baz
5.  Require only files will have a full demo of it's method or methods.  Code in a single file may be split into multiple tests, named after the method.
6.  Alias files will have a simple demo, and a reference to the file it aliases

**Comment by trans** [comment]
That seems about right. 

On 3, if there are tests for an alias, that's okay. I would say it *at least* has to have a single test to confirm the alias, but while unnecessary additional redundancy does hurt anything. In other words, I wouldn't worry about deleting tests for aliases if they already exist. But it should be clearly documented that it is an alias in the test code.

On 5, I think that is correct even though it differs from how we handle tests, b/c we want the demos to discoverable alphabetically by method. Whereas for tests we want the test code to correspond directly to where the code it tests appears under lib.

**Comment by trans** [comment]
I just updated the CONTRIBUING file, and added you points to it. Thanks for that. Still need to work on that file a bit, but its much more up to date now.
