### ISSUE TITLE
String#snakecase breaks Devise

### ISSUE THREAD

**Issue by lunrfarsde** [rubyworks/facets#240]
`String#snakecase` breaks Devise because of this line:

    alias_method :underscore, :snakecase

**Comment by trans** [comment]
Taking a quick glance at Devise, I see it is a Rails library. So the problem (almost certainly) lies in an incompatibility between Facets' and ActiveSupport's definition of `#underscore`. The simple fix is to make sure that any Facets extensions are loaded *before* ActiveSupport. This allows ActiveSupport to override any extensions made by Facets, giving it the last word, so to speak. This is the recommended approach for using Facets with Rails in general.

**Comment by trans** [comment]
Btw, here is a tip on how to do this. https://github.com/rubyworks/facets/wiki/TIP%3A-Facets-on-Rails This hasn't been update for a while, so it might be that new versions of Rails have (once again)  changed such that the solution presented no longer works. Please let me know if you discover this to be the case and if you find a new solution to achieve the same result so I can update the tip. Thanks, and HTH.

**Comment by lunrfarsde** [comment]
The solution did not work. But i found out that the problem is in the integration code of 'activeadmin' with 'devise'. I will try to take a look at the source code and try to learn more.

**Comment by lunrfarsde** [comment]
The problem is solved by adding `require 'facets/string'` to the `config/boot.rb`. The document needs updating as such.

**Comment by trans** [comment]
Nice. Thank you. I will update the document. Think I'll even add a note about it the README.
