### ISSUE TITLE
string similarity get over 1 result

### ISSUE THREAD

**Issue by acbyac** [rubyworks/facets#244]
```
> 'aaa asdf'.similarity('asdf aaa')
 => 1.125
```

strange result from similarity function. not sure if its a special case

**Comment by trans** [comment]
You are quite right. I did not write this algorithm so even after reviewing the code I am not quite sure what is causing it to be off. But after a number of tries I was unable to create a result that was off by more than one between the numerator and denominator of the final score, so, everything being relative I simply added 1 to the denominator of the calculation. Unless there is larger hole in this algorithm than is apparent, that should ensure a score between 0 and 1.

Thanks for reporting.
