### ISSUE TITLE
Keep Hash#symbolize_keys and Hash#stringify_keys ?

### ISSUE THREAD

**Issue by trans** [rubyworks/facets#245]
Consider deprecating `Hash#symbolize_keys` and `Hash#stringify_keys`. They seem a bit to magical and `#rekey` is probably the better approach in any case.

Even if we do deprecate them, we can still keep them as non-core requires.

**Comment by tilo** [comment]
I think that's not a good idea -- using this outside of Rails is very useful!

Instead they should be fixed!
https://github.com/rubyworks/facets/issues/253

**Comment by trans** [comment]
Okay.

**Comment by ioquatix** [comment]
Personally I think you could make them non-core. They are useful.. but they also indicate some poor API usage..

**Comment by ioquatix** [comment]
(E.g. JSON and YAML I believe have ways to load strings as symbols, which would be a lot more efficient.)
