### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by codeindulgence** [rubyworks/facets#252]
It's been a year since 3.0.0 was released and it looks like a few methods have been added since.
Can we get a new gem release?

**Comment by CyborgMaster** [comment]
I concur.  There is a bug in ergo that causes a crash that was fixed back in February 2015.  May we please have a new release.

**Comment by trans** [comment]
I'll do it this weekend. I've been meaning to do it since the beginning of the year, but have been busy with other things.

**Comment by CyborgMaster** [comment]
Thanks a ton! I really appreciate it.

**Comment by trans** [comment]
Just release 3.1.0. Let me know if you run into any problems so I can fix ASAP. Thanks!
