### ISSUE TITLE
hashify.rb bug

### ISSUE THREAD

**Issue by SilverPhoenix99** [rubyworks/facets#255]
`alias :assoc, :associate` is not parsing correctly in Ruby v2.2 because of the comma.

**Comment by trans** [comment]
Thanks. Looks like this was fixed some time ago though.

https://github.com/rubyworks/facets/blob/5569b03b4c6fd25897444a266ffe25872284be2b/lib/core/facets/enumerable/hashify.rb#L106

If it hasn't made it into a release yet, not to worry, I will be doing a new release soon.
