### ISSUE TITLE
Small typo in the main README

### ISSUE THREAD

**Issue by shevegen** [rubyworks/facets#257]
Yo trans, just a small typo in the main readme:

"If you have any extension methods, classes or modules that you think have very general applicability and would like to see them included in this project, don't hesitiate to submit."

I believe that "heistiate" should be "hesitate".

By the way, facets is a great idea, I have been following it since years. Hopefully one day we can generalize it and find some means to make it a (the?) primary-addon; this may need some community-based decision for extending it too such as voting for additions but anyway, this is off-topic sorry, I just wanted to report the typo really.

**Comment by ioquatix** [comment]
Nice. Can you submit a PR?

**Comment by ioquatix** [comment]
.. Just hit edit on the README.md and it should only take like 30 seconds. Then you will be recorded for time immemorial as a contributor :D

**Comment by trans** [comment]
Fixed thanks!
