### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by ioquatix** [rubyworks/facets#262]
I think that this project has convoluted licensing. Have you considered simply using the MIT license?

**Comment by trans** [comment]
I think we can switch it all over to BSD2 now.  The same license Ruby itself is now under. I'll work on it. Thanks for bringing it up.

**Comment by ioquatix** [comment]
Thats okay and I think it would be great. The GPL is really bad for code like this.

The way I see it, the GPL preserves the rights of the users over the rights of the developers. The BSD/MIT license preserves the rights of the developers over the rights of the users. The bias is small, but as I'm a developer, I prefer the BSD/MIT license, and ultimately I prefer the MIT license for it's simplicity and it's also the most commonly used license.

**Comment by trans** [comment]
MIT is good too. But I think it makes the most sense to keep it the same as Ruby's license. MIT and BSD are nearly the same in any case.

**Comment by trans** [comment]
Normalization is done, and the code should sufficiently reflect that (hopefully I didn't miss anything). 

All code is now officially under the BSD-2 Clause License!
