### ISSUE TITLE
prefer require_relative

### ISSUE THREAD

**Issue by ioquatix** [rubyworks/facets#263]
Have you considered moving to require_relative? Not only is it faster, it's also more logical, and less chance of unexpected behaviour.

**Comment by trans** [comment]
I'm all for that. It is just a matter of doing it.

**Comment by ioquatix** [comment]
Okay, it's easy to do.

**Comment by ioquatix** [comment]
I see that usage of `require_relative` is pretty good in the source code currently. I'll refactor it where it makes sense.
