### ISSUE TITLE
Facets "Essentials"

### ISSUE THREAD

**Issue by trans** [rubyworks/facets#44]
Another interesting idea would be to mark a very very few libs as "essential" like "you use these every day" File.write would be one for me. i.e. something like a

```
require 'facets/essentials'
```

-Roger Pack

**Comment by ioquatix** [comment]
"Essentials" for one person is going to be different for another person. I don't think this is a good idea. I like the idea in general, but I can't see any good way to implement it.

**Comment by ioquatix** [comment]
Vote to close.

**Comment by ioquatix** [comment]
I see we now have this. Great, let's just leave it as is for now. Perhaps some documentation on the readme might make sense?
